name: forum_firebase_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  go_router: ^14.8.1
  cloud_firestore: ^5.6.5
  image_picker: ^1.1.2
  easy_design_system: ^0.0.28
  provider: ^6.1.2
  firebase_ui_firestore: ^1.7.1
  firebase_storage: ^12.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
